### ISSUE TITLE
claudia update fails with latest fastify version

### ISSUE THREAD

**Issue by veedeo** [claudiajs/example-projects#28]
```
TypeError: "listener" argument must be a function
    at _addListener (events.js:239:11)
    at Server.addListener (events.js:297:10)
    at new Server (_http_server.js:269:10)
    at Object.createServer (http.js:34:10)
```

**Comment by kwalski** [comment]
any fix for this?

**Comment by veedeo** [comment]
I don't remember what was the problem exactly. but this is correct entry point for latest version:
```
import Fastify from 'fastify';
import awsServerlessExpress from 'aws-serverless-express';
import api from './api';

const app = Fastify({
  serverFactory(handlerMethod) {
    return awsServerlessExpress.createServer(handlerMethod);
  },
});
api(app);
app.ready(() => console.log('Ready'));

export function handler(event, context) {
	return awsServerlessExpress.proxy(app.server, event, context);
}
```

**Comment by kwalski** [comment]
@veedeo your guidance has been mighty helpful! Thank you 👍

**Comment by kwalski** [comment]
I recommend calling awsServerlessExpress.proxy inside app.ready callback, as in my case, proxy was calling fastify routes prematurely

**Comment by veedeo** [comment]
Can you share the code?

**Comment by kwalski** [comment]
in my api, I was creating a database connection during fastify initialization which was delaying fastify readiness before awsServerlessExpress.proxy call and fastify's route hanler was not being called. The following change will ensure fastify is ready

```
import Fastify from 'fastify';
import awsServerlessExpress from 'aws-serverless-express';
import api from './api';

const app = Fastify({
  serverFactory(handlerMethod) {
    return awsServerlessExpress.createServer(handlerMethod);
  },
});
api(app);

export function handler(event, context) {
  app.ready((err) => { 
       console.log(err?err:'Ready');
       return awsServerlessExpress.proxy(app.server, event, context);
  });
}
```

**Comment by adrai** [comment]
https://github.com/adrai/fastify/blob/master/docs/Serverless.md
PR is in progress: https://github.com/fastify/fastify/pull/1564
claudia example is updated: https://github.com/claudiajs/example-projects/tree/master/fastify-app-lambda

**Comment by adrai** [comment]
https://www.fastify.io/docs/master/Serverless/
